apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
  labels:
    app: nginx
    type: nginx
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        type: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.26
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
  selector:
    matchLabels:
      app: nginx
  replicas: 6
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
