apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
  namespace: nginx
  labels:
    app: nginx
    type: nginx
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        type: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.26
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
  selector:
    matchLabels:
      app: nginx
  replicas: 6
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx  
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  nginx-ingress
  namespace: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  
spec:
  ingressClassName: nginx
  rules:
  - host: nginx.flinox.com.br
    http:
      paths:
      - backend:
          service:
            name:  nginx-svc
            port:
              number: 80
        path: /
        pathType: Prefix
